version: '2'

services:
   java:
     build: .
     restart: always
     depends_on:
       - mysql
     links:
       - mysql

   mysql:
     image: mysql/mysql-server
     restart: always
     volumes:
       - ./mysql:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=welcome1
       - MYSQL_DATABASE=docker
       - MYSQL_USER=docker
       - MYSQL_PASSWORD=welcome1
       - MYSQL_ROOT_HOST=172.20.0.3
