version: '2'

services:
   nodejs:
     build: .
     restart: always
     depends_on:
       - mongodb
     links:
       - mongodb

   mongodb:
     image: mongo
     restart: always
     volumes:
       - ./mongodb:/data/db
     ports:
       - "27017:27017"

   proxy:
     image: amouat/proxy:1.0
     links:
       - nodejs
     ports:
       - "80:80"
     environment:
       - NGINX_HOST=45.55.251.164
       - NGINX_PROXY=http://nodejs:3000

   logspout:
     image: amouat/logspout-logstash
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock
     ports:
       - "8000:80"       

volumes:
    db_data:
